#387
ARUP-CAS/aiscr-webamcr pull request #2125
Opened 2024-07-14 18:34 UTC by pesikj

#387

2024-07-21 10:03 UTC, motyc requested changes

2024-07-21 10:03 UTC, motyc commented on webclient/services/mailer.py
> +            historie__historie__datum_zmeny__lt=timezone.now() + timedelta(days=-1),
@pesikj Jestli to dobře chápu, tak zde se to bude řídit konkrétním časem, nikoli obecným datumem. To ale není ideální, protože to může vést k tomu, že se některá oznámení přeskočí (kvůli odlišnému času spuštění apod.). Je třeba podmínku nastavit tak, aby to bylo: `datum.dnes - 2 dny < historie.datum_zmeny < datum.dnes`. Možná to tak ale je, jen to špatně čtu.

2024-07-21 10:03 UTC, motyc commented on webclient/services/mailer.py
> +            historie__historie__datum_zmeny__lt=timezone.now() + timedelta(days=-1),
@pesikj dtto jako v komentáři výše.

2024-07-22 19:51 UTC, pesikj commented on webclient/services/mailer.py
> +            historie__historie__datum_zmeny__lt=timezone.now() + timedelta(days=-1),
Opraveno.

2024-07-22 20:08 UTC, motyc commented
@pesikj Ještě jsem udělal drobnou korekci v https://github.com/ARUP-CAS/aiscr-webamcr/commit/5c27f6b69a07c9e1e72f5e8772c9f4a775fcffa1. Jinak je to za mne ok.

2024-07-22 20:09 UTC, motyc submitted a review, later dismissed

2024-07-22 20:38 UTC, motyc approved these changes

2024-07-22 20:50 UTC, merged