#2139 Přidaný kontejner Fedora pro dev
ARUP-CAS/aiscr-webamcr pull request #2164
Opened 2024-07-24 10:09 UTC by jhavrlant

2024-07-24 10:21 UTC, motyc requested changes

2024-07-24 10:21 UTC, motyc commented on fedora/inputs/amcr.xsd
@jhavrlant Tento soubor by se v rámci GH mohl brát z https://github.com/ARUP-CAS/aiscr-webamcr/blob/dev/webclient/xml_generator/definitions/amcr.xsd, ať to zbytečně neduplikujeme. Také nebude hrozit, že se nám rozejdou verze.

2024-07-24 16:33 UTC, pesikj approved these changes

2024-07-25 07:10 UTC, motyc approved these changes

2024-07-25 07:10 UTC, merged