Oprava #2290 a #2291
ARUP-CAS/aiscr-webamcr pull request #2304
Opened 2024-09-04 08:27 UTC by jhavrlant

Navazuje na #1744

2024-09-04 09:08 UTC, motyc approved these changes

2024-09-06 07:09 UTC, pesikj requested changes

2024-09-06 07:09 UTC, pesikj commented on webclient/projekt/views.py
> +    except Exception as e:
Já bych doporučil odchytávat konkrétní chybu a ne obecnou `Exception`, pokud je to možné.

2024-09-07 19:51 UTC, motyc commented
@pesikj Tady prosím ještě o finální review po úpravách od Honzy.

2024-09-09 18:25 UTC, pesikj approved these changes

2024-09-09 18:26 UTC, pesikj approved these changes

2024-09-09 18:27 UTC, merged