Added modal for adding/modification of submit date #2313
ARUP-CAS/aiscr-webamcr pull request #2334
Opened 2024-09-08 18:27 UTC by pesikj

#2313

2024-09-08 20:03 UTC, motyc requested changes
@pesikj Všiml jsem si zde dvou věcí:
- PR zahrnuje i části úprav pro #2245, což není úplně dobré kvůli testování atd. - šlo by to ještě oddělit, ať v tom není zmatek?
- na schůzce jsme se dohodli, že se pro oznámení udělá nový typ údaje v historii `POZ` a že to půjde jen zapisovat nově spolu s poznámkou (takto to je popsáno v #2313). Z kódu vyplývá, že se to řeší jako původní navržené řešení (přidání či editace `Px0`, tj. `OZNAMENI_PROJ` + poznámka). Může to tak asi zůstat, protože mě nenapadá, v čem by to mohlo být problematické. Případné verzování řeší Fedora, takže změna bude případně stopovatelná, kdyby s tím byl problém.

2024-09-09 20:59 UTC, pesikj commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
@motyc Tohle je zatím draft. Zakládat jsem to z Pycharmu a zapomněl to nastavit.

Co se týká typu, tak pamatuji si dobře, že zavedeme nový typ záznamu v historii? Obecně myslím, že bude potřeba řešit modifikaci, protože uživatel může zadat hodnotu chybně a nechceme poté vkládat další záznam.

2024-09-09 21:04 UTC, motyc commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
@pesikj Ok, tím se to vysvětluje, tak počkám na finální verzi.

Jinak k tomu typu - no domluvili, ale právě z kódu mi přijde, že to tak není napsané :) Já na tom vlastně netrvá, proto jak píšu výše, pokud tam nevidíš nějaký problém Ty, klidně se to může být ten typ `OZNAMENI_PROJ`, jak to máš udělané. Jen mě to prostě zmátlo, když jsme se domluvili původně jinak a chtěl jsem si potvrdit, jak je to myšleno. Jinak s tou opravou je to dobrý point.

2024-09-11 19:18 UTC, pesikj commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
@motyc Já jsem si to spíše špatně zapamatoval. Přidání nového stavu je lepší řešení, protože jinde historii neměníme a může se nám nebo uživatelům někdy hodit umět dohledat datum vytvoření záznamu v aplikaci, aniž by bylo nutné stahovat metadata z Fedory.

2024-09-11 21:10 UTC, motyc commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
Ok, souhlas.

2024-09-23 12:36 UTC, motyc requested changes
@pesikj Mimo konkrétní komentáře prosím ještě zajistit, aby se PX0M objevovalo také v seznamu filtrace podle historie (https://amcr-test.aiscr.cz/projekt/vyber) a příslušná filtrace fungovala.

2024-09-23 12:36 UTC, motyc commented on webclient/core/forms.py
Nepatří to spíš do https://github.com/ARUP-CAS/aiscr-webamcr/pull/2361?

2024-09-23 12:36 UTC, motyc commented on webclient/core/repository_connector.py
Nepatří to spíš do https://github.com/ARUP-CAS/aiscr-webamcr/pull/2361?

2024-09-23 12:36 UTC, motyc commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
@pesikj Stále asi zůstal chybný label.

2024-09-23 12:36 UTC, motyc commented on webclient/projekt/forms.py
> +        help_text=_("projekt.forms.editProjekt.datumZahajeni.tooltip"),
@pesikj Asi chybný tooltip?

2024-09-23 12:36 UTC, motyc commented on webclient/projekt/forms.py
> +            "poznamka": _("projekt.forms.editProjekt.poznamka.tooltip"),
@pesikj Asi chybný tooltip?

2024-09-23 12:36 UTC, motyc commented on webclient/templates/toolbar_projekt.html
> +          {% endif %}
@pesikj Prosím posunout v rámci menu za `generovat_potvrzeni`

2024-09-24 06:44 UTC, pesikj commented on webclient/projekt/forms.py
> +            "poznamka": _("projekt.forms.editProjekt.poznamka.tooltip"),
Opraveno.

2024-09-24 06:44 UTC, pesikj commented on webclient/projekt/forms.py
> +        help_text=_("projekt.forms.editProjekt.datumZahajeni.tooltip"),
Opraveno.

2024-09-24 06:44 UTC, pesikj commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
Opraveno.

2024-09-24 06:46 UTC, pesikj commented on webclient/core/repository_connector.py
Je to spíše úprava logování, které způsobuje problémy. Není to v rámci zadání #2361, ale všiml jsem si té chyby při práci na tom issue.

2024-09-24 06:49 UTC, pesikj commented on webclient/core/forms.py
To je oprava obecné chyby. Použití klíče `message` ve slovníku u parametru `extra` způsobuje chybu, toto klíčové slovo je vyhrazené a hodnotu není možné přepsat.

2024-09-24 08:34 UTC, motyc commented on webclient/core/forms.py
Ok, díky za vysvětlení.

2024-09-24 08:34 UTC, motyc commented on webclient/core/repository_connector.py
Ok, díky za vysvětlení.

2024-09-24 08:36 UTC, motyc commented on webclient/projekt/forms.py
> +            "datum_ukonceni": _("projekt.forms.ukoncitVTerenu.datumUkonceni.label"),
Ok, díky za vysvětlení.

2024-09-25 22:59 UTC, motyc approved these changes

2024-09-26 08:04 UTC, jnihnat commented on webclient/projekt/forms.py
> +        }
@pesikj pridej jeste label pro poznamku

2024-09-26 08:20 UTC, jnihnat commented on webclient/projekt/views.py
> +                histore.save()
@pesikj  ma nejaky vyznam mit save tady a o 3 radky dolu taky?

2024-09-30 10:55 UTC, pesikj commented on webclient/projekt/views.py
> +                histore.save()
Otestoval jsem a není potřeba.

2024-09-30 10:55 UTC, pesikj commented on webclient/projekt/forms.py
> +        }
Přidáno.

2024-09-30 12:18 UTC, merged