bug/2376
ARUP-CAS/aiscr-webamcr pull request #2386
Opened 2024-09-24 19:53 UTC by jnihnat

#2376

2024-09-24 21:14 UTC, motyc requested changes
Ještě to bude chtít mrknout na ty výběry (viz https://github.com/ARUP-CAS/aiscr-webamcr/issues/2376#issuecomment-2372384086). Ale je možné, že to přímo nesouvisí.

2024-09-24 21:14 UTC, motyc commented on webclient/dokument/templates/dokument/dokument_table_row.html
@jnihnat Jen pro ujištění - toto pokrývá tabulky s dokumenty u projektů i AZ (akce, lokality), že ano?

2024-09-25 16:14 UTC, jnihnat commented on webclient/dokument/templates/dokument/dokument_table_row.html
Jo je to jen jedno misto pro vsechny.

2024-09-25 16:21 UTC, motyc approved these changes

2024-09-25 19:28 UTC, pesikj approved these changes

2024-09-25 22:57 UTC, merged