Feat/pid doi
ARUP-CAS/aiscr-webamcr pull request #2641
Opened 2024-12-01 15:20 UTC by pesikj

#2616 #2594 #2591

2025-01-11 13:49 UTC, motyc requested changes

2025-01-11 13:49 UTC, motyc commented on webclient/doi/model_serializers.py
> +    def serialize_hide(self):
Tady by myslím mělo být `serialize_delete`, resp. by se to mělo vkládat jen při mazání. Bude to nějaké pomotané.

2025-01-11 13:49 UTC, motyc commented on webclient/doi/model_serializers.py
> +            # DataCite request may be called before the history record is created
Je dobře, že se s tím počítá, ale kdy ses s tím v praxi setkal, že to dělalo problém? Je to myslím spíš potenciální chyba a mělo by to vrátit výjimku.

2025-01-11 13:49 UTC, motyc commented on webclient/doi/model_serializers.py
> +    def _serialize_geo_locations(self):
Není náhodou opomenuto ošetření situace, kdy přístupnost není anonym? Pokud ano, asi to bude platit i pro další situace (viz soubory s definicemi).

2025-01-11 13:49 UTC, motyc commented on webclient/doi/model_serializers.py
> +                        "affiliationIdentifier": f"https://ror.org/{AIS_AMCR.ident_cely}",
Viz poznámka k `AIS_AMCR`

2025-01-11 13:49 UTC, motyc commented on webclient/doi/model_serializers.py
> +                        "publisherIdentifier": f"https://ror.org/{AIS_AMCR.ror}",
Viz poznámka k AIS_AMCR

2025-01-11 13:49 UTC, motyc commented on webclient/doi/model_serializers.py
> +            if self.record.archeologicky_zaznam and self.record.archeologicky_zaznam.stav == AZ_STAV_ARCHIVOVANY:
Téhle podmínce nerozumím - proč tu je? Pokud tato funkce je pro lokalitu, pak to nedává smysl, ale možná to špatně chápu.

2025-01-11 13:49 UTC, motyc commented on webclient/doi/verificators.py
Verifikace pro Wikidata nejde dělat, nebo je opomenutá? https://www.wikidata.org/wiki/Wikidata:REST_API

2025-01-11 13:49 UTC, motyc commented on webclient/doi/__init__.py
Byl by ještě problém celou aplikaci místo `doi` nazvat `pid`? Ono se tam totiž definují různé druhy PID a bylo by méně matoucí, kdyby se to pojmenovalo takto univerzálně.

2025-01-11 13:49 UTC, motyc commented on webclient/projekt/views.py
> +                item.dokument.doi_publish()
Tady by myslím mělo být `doi_update`, ne?

2025-01-12 13:19 UTC, pesikj commented on webclient/doi/model_serializers.py
> +            # DataCite request may be called before the history record is created
Ono se to stane vždy při prvotní archivaci, protože DOI se generuje jako první (viz třeba zde: https://github.com/ARUP-CAS/aiscr-webamcr/blob/e627e5131c089bb54c1264ac61d1fdc35849e029/webclient/pas/views.py#L599).

2025-01-12 15:52 UTC, pesikj commented on webclient/arch_z/views.py
> +                item.dokument.doi_publish()
Ano, opraveno.

2025-01-12 15:53 UTC, pesikj commented on webclient/doi/model_serializers.py
> +    def serialize_hide(self):
Opraveno.

2025-01-12 15:53 UTC, pesikj commented on webclient/doi/model_serializers.py
> +    def _serialize_geo_locations(self):
Chybělo to, opraveno.

2025-01-12 15:53 UTC, pesikj commented on webclient/doi/model_serializers.py
> +                        "affiliationIdentifier": f"https://ror.org/{AIS_AMCR.ident_cely}",
Opraveno.

2025-01-12 15:54 UTC, pesikj commented on webclient/doi/model_serializers.py
> +                        "publisherIdentifier": f"https://ror.org/{AIS_AMCR.ror}",
Opraveno.

2025-01-12 15:54 UTC, pesikj commented on webclient/doi/model_serializers.py
> +            if self.record.archeologicky_zaznam and self.record.archeologicky_zaznam.stav == AZ_STAV_ARCHIVOVANY:
Opraveno.

2025-01-12 15:54 UTC, pesikj commented on webclient/doi/verificators.py
Doplněno.

2025-01-12 15:54 UTC, pesikj commented on webclient/doi/__init__.py
Přejmenováno.

2025-01-12 15:54 UTC, pesikj commented on webclient/projekt/views.py
> +                item.dokument.doi_publish()
Opraveno.

2025-01-12 16:21 UTC, motyc commented on webclient/doi/model_serializers.py
> +AIS_AMCR = Organizace.objects.get(ident_cely="ORG-000091")
Ok, jen bych zrovna tohle nutně nedával do secrets, protože se s nimi složitěji pracuje a bude to na všech prostředích ve výsledku stejné. Dal bych to nastavení klidně pevně jako řetězec do kódu. Zatím tam lze dát ten https://ror.org/0287jta43 a pak to vyměníme za správný.

2025-01-12 16:28 UTC, motyc commented on webclient/doi/model_serializers.py
> +            # DataCite request may be called before the history record is created
Aha, už je mi to jasné.

2025-01-13 18:26 UTC, jnihnat requested changes

2025-01-13 18:26 UTC, jnihnat commented on webclient/dokument/models.py
> +    def get_komponenty(self, arch_z_status=None):
Asi bych to prejmenoval na get komponenty for status alebo except status

2025-01-13 18:26 UTC, jnihnat commented on webclient/pid/client.py
> +        if isinstance(self.record, Dokument):
Nebylo by lepsi mit mapu class:serializer nez else if?

2025-01-13 18:26 UTC, jnihnat commented on webclient/pid/client.py
> +        return str(response.status_code).startswith("2")
Co kdyz to jen vrati 500? Nebylo by lepsi checkovat 200 vs 404 vs ostatni?

2025-01-13 18:30 UTC, motyc commented on webclient/arch_z/views.py
> +            if item.dokument.stav == AZ_STAV_ARCHIVOVANY:
Nene, toto je dobře. Jde o aktualizaci souvisejících publikovaných dokumentů při archivaci akce.

2025-01-13 18:33 UTC, jnihnat commented on webclient/arch_z/views.py
> +            if item.dokument.stav == AZ_STAV_ARCHIVOVANY:
Ale v porovnani je stav dokumentu na konstantu stavu AZ

2025-01-13 18:34 UTC, motyc commented on webclient/arch_z/views.py
> +            if item.dokument.stav == AZ_STAV_ARCHIVOVANY:
No jo, máš pravdu - ano, to bude překlep. Díky :)

2025-01-13 18:50 UTC, pesikj commented on webclient/dokument/models.py
> +    def anonym(self):
To je jen placeholder, až to @jhavrlant doimplementuje :-)

2025-01-13 18:54 UTC, motyc commented on webclient/dokument/models.py
> +    def anonym(self):
@pesikj Tak možná v takových případech prosím nechávej komentáře, ať to je jasné a nezapomeneme... Dík

2025-01-14 16:20 UTC, jhavrlant requested changes

2025-01-14 16:20 UTC, jhavrlant commented on webclient/arch_z/views.py
> +            if az.lokalita and az.stav == AZ_STAV_ARCHIVOVANY:
Mě to zde při vrácení Samostatné akce hází chybu.
Všude kde se vyskytuje az.lokalita a pracuje se se Samostatnou akcí to hlásí ArcheologickyZaznam has no lokalita

2025-01-14 16:41 UTC, motyc commented
@pesikj Bylo by asi bezva, kdybys sem zapracoval zbylé opravy, pak bych to mergnul (+ na základě toho publikoval aplha-1 verzi) a následně bychom teprve pokračovali v tom #2687

2025-01-15 07:12 UTC, pesikj commented on webclient/dokument/models.py
> +    def get_komponenty(self, arch_z_status=None):
Ten parametr `arch_z_status` je nepovinný, tak nevím, jestli by to spíše nebylo matoucí.

2025-01-15 07:41 UTC, pesikj commented on webclient/core/admin.py
> +                        if isinstance(record, Dokument):
Šlo by to přepsat nějak takto, ale nevím, jestli je to přehlednější.
```py
def _get_model_mappings(self):
        return {
            Dokument: {
                "key": "doi",
                "archive_status": D_STAV_ARCHIVOVANY,
                "actions": {
                    "post_publish": lambda record: (not record.doi, record.doi_publish, record.set_doi),
                    "put_publish": lambda record: (record.doi, record.doi_publish, None),
                    "hide": lambda record: (record.doi and record.stav != D_STAV_ARCHIVOVANY, record.doi_hide, None),
                    "update": lambda record: (record.doi, record.doi_update, None),
                },
            },
            ArcheologickyZaznam: {
                "key": "igsn",
                "archive_status": AZ_STAV_ARCHIVOVANY,
                "actions": {
                    "post_publish": lambda record: (not record.lokalita.igsn and record.stav == AZ_STAV_ARCHIVOVANY, record.lokalita.igsn_publish, record.lokalita.set_igsn),
                    "put_publish": lambda record: (record.lokalita.igsn, record.lokalita.igsn_publish, None),
                    "hide": lambda record: (record.lokalita.igsn and record.stav != AZ_STAV_ARCHIVOVANY, record.lokalita.igsn_hide, None),
                    "update": lambda record: (record.lokalita.igsn, record.lokalita.igsn_update, None),
                },
            },
            SamostatnyNalez: {
                "key": "igsn",
                "archive_status": SN_ARCHIVOVANY,
                "actions": {
                    "post_publish": lambda record: (not record.igsn and record.stav == SN_ARCHIVOVANY, record.igsn_publish, record.set_igsn),
                    "put_publish": lambda record: (record.igsn, record.igsn_publish, None),
                    "hide": lambda record: (record.igsn and record.stav != SN_ARCHIVOVANY, record.igsn_hide, None),
                    "update": lambda record: (record.igsn and record.stav != SN_ARCHIVOVANY, record.igsn_update, None),
                },
            },
        }
        ```

2025-01-15 07:57 UTC, pesikj commented on webclient/arch_z/views.py
> +            if item.dokument.stav == AZ_STAV_ARCHIVOVANY:
Opraveno.

2025-01-15 07:57 UTC, pesikj commented on webclient/arch_z/views.py
> +        "text": _("dokument.views.archivovat.doi_exists_warning") if az.lokalita and az.lokalita.igsn_exists else None,
Opraveno.

2025-01-15 07:57 UTC, pesikj commented on webclient/core/admin.py
> +                        record = get_record_from_ident(ident_cely)
Potom funkce vráti None, ale přidal jsem k tomu výpis, aby to v tabulce nebylo prázdné.

2025-01-15 07:57 UTC, pesikj commented on webclient/dokument/models.py
> +    def anonym(self):
Přidal jsem.

2025-01-15 07:58 UTC, pesikj commented on webclient/pid/client.py
> +        if isinstance(self.record, Dokument):
Upravil jsem to.

2025-01-15 07:58 UTC, pesikj commented on webclient/pid/client.py
> +        return str(response.status_code).startswith("2")
Upravil jsem.

2025-01-15 07:58 UTC, pesikj commented on webclient/arch_z/views.py
> +            if az.lokalita and az.stav == AZ_STAV_ARCHIVOVANY:
Změnil jsem na try-catch.

2025-01-15 07:59 UTC, pesikj commented
> @pesikj Bylo by asi bezva, kdybys sem zapracoval zbylé opravy, pak bych to mergnul (+ na základě toho publikoval aplha-1 verzi) a následně bychom teprve pokračovali v tom #2687

Souhlasím. Počkám, až se kluci vyjádří k opravám a pak dám merge.

2025-01-15 15:41 UTC, jhavrlant approved these changes

2025-01-15 16:16 UTC, jnihnat commented on webclient/core/admin.py
> +                        if isinstance(record, Dokument):
Ono se opakuji i ty actions, ale uz necham na tobe co se ti zda lepsi.

2025-01-15 19:52 UTC, pesikj commented on webclient/doi/model_serializers.py
> +AIS_AMCR = Organizace.objects.get(ident_cely="ORG-000091")
Přesunuto do konstant.

2025-01-15 19:54 UTC, motyc approved these changes

2025-01-15 19:54 UTC, merged