Bug/810 hlidaci pes
ARUP-CAS/aiscr-webamcr pull request #897
Opened 2023-02-05 19:00 UTC by jnihnat

#810

2023-02-06 18:32 UTC, jnihnat commented
@pesikj  @sedmar 
je potreba potom pridat secret na produkci pro redis password. Rovnako prosim skontrolujte ty dockre, ci jsem neco neopomnel, hlavne po tom jak si to Marek prerabal. 
Vysledky taskov je potom mozne vydet v adminu pod task results. Pridal jsem to do budoucna, kdy to mozna bude zadane a tedka aspon na kontrolu. Pripadne odebrat to bude jednoduche.

2023-02-13 09:08 UTC, pesikj requested changes

2023-02-13 15:47 UTC, jnihnat commented on .github/workflows/ci.yml
> +        python manage.py migrate heslar --skip-checks --settings=webclient.settings.git_test
mnel jsem problem ze git container nepoznal redis:6379, tak som mu musel dat localhost. Tedka mne jeste napada to udelat cez ENV variable a nemit tam navic ten git_test settings. Dej vedet co se ti libi vic.

2023-02-13 15:47 UTC, jnihnat commented on webclient/notifikace_projekty/templates/notifikace_projekty/pes_list.html
> +          var options = Object.assign(defaults, {modalID: "modal-form",
predelam na const, mnelo by to fungovat.

2023-02-14 09:11 UTC, pesikj commented on webclient/notifikace_projekty/templates/notifikace_projekty/pes_list.html
> +          var options = Object.assign(defaults, {modalID: "modal-form",
Super

2023-02-14 09:14 UTC, jnihnat commented on webclient/notifikace_projekty/templates/notifikace_projekty/pes_list.html
> +          var options = Object.assign(defaults, {modalID: "modal-form",
predelane v novem commitu

2023-02-14 09:23 UTC, pesikj commented on .github/workflows/ci.yml
> +        python manage.py migrate heslar --skip-checks --settings=webclient.settings.git_test
Tak tam prosím zkus dát tu ENV proměnnou, díky.

2023-02-14 13:07 UTC, jnihnat commented on .github/workflows/ci.yml
> +        python manage.py migrate heslar --skip-checks --settings=webclient.settings.git_test
Predelano a funguje.

2023-02-14 17:10 UTC, pesikj approved these changes

2023-02-14 17:11 UTC, merged